version: '1' 
services: 
  mypythonapp: 
    build: 
      context: .
    environment: 
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CLOUD_API=${CLOUD_API}
    command: 
      python main.py